name: supinn
channels:
  - defaults
dependencies:
  - python==3.9
  - numpy==1.23.1
  - scipy==1.9.1
  - matplotlib==3.5.2
  - pip
  - pip:
      - tensorflow==2.15
      - tensorflow-probability==0.23
      - deepxde==1.11.1
  
